### ISSUE TITLE
test data

### ISSUE THREAD

**Issue by philsmoot** [mrmattuschka/DeePiCt#20]
Is there test data we can download to use or that matches the 2d_cnn and 3d_cnn sample scripts provided in the README's?

**Comment by frosinastojanovska** [comment]
Hi @philsmoot, you can use the test data that is provided in the [Dropbox folder](https://www.dropbox.com/sh/oavbtcvusi07xbh/AADmnwIIsLUH1DuJ03IdDO7Ta?dl=0) or the available data from [EMPIAR](https://www.ebi.ac.uk/empiar/EMPIAR-10988/)

**Comment by philsmoot** [comment]
Do you know which EMPIAR image set?  i.e. 1, 2, 3…

Thanks, Phil

From: Frosina Stojanovska ***@***.***>
Date: Thursday, May 2, 2024 at 8:52 AM
To: ZauggGroup/DeePiCt ***@***.***>
Cc: Phil Smoot ***@***.***>, Mention ***@***.***>
Subject: Re: [ZauggGroup/DeePiCt] test data (Issue #20)

Hi @philsmoot<https://github.com/philsmoot>, you can use the test data that is provided in the Dropbox folder<https://www.dropbox.com/sh/oavbtcvusi07xbh/AADmnwIIsLUH1DuJ03IdDO7Ta?dl=0> or the available data from EMPIAR<https://www.dropbox.com/sh/oavbtcvusi07xbh/AABCSionWxE3jHVX7TpwtQqna/Test_data?dl=0&subfolder_nav_tracking=1>

**Comment by frosinastojanovska** [comment]
I updated the second link, it's EMPIAR-10988

**Comment by philsmoot** [comment]
Thanks.  There are 6 different imaging sets on that page.  Is there one in particular I should download?



From: Frosina Stojanovska ***@***.***>
Date: Thursday, May 2, 2024 at 11:12 AM
To: ZauggGroup/DeePiCt ***@***.***>
Cc: Phil Smoot ***@***.***>, Mention ***@***.***>
Subject: Re: [ZauggGroup/DeePiCt] test data (Issue #20)

I updated the second link, it's EMPIAR-10988

**Comment by frosinastojanovska** [comment]
I guess you want the reconstructed VPP or defocus tomograms, since the other files are the files from the tomogram reconstruction steps
